### ISSUE TITLE
Mild mismatch between DESCRIPTION file, commit history and JOSS authors list

### ISSUE THREAD

**Issue by martinmodrak** [NSAPH-Software/GPCERF#67]
This might actually not be a real issue and just need a little bit of explanation to resolve.

The DESCRIPTION file has Tanujit, Dey as a contributor to the package, but they are not listed as co-authors of the JOSS paper.

Tanujit, Dey and Danielle, Braun are listed in DESCRIPTION but have made no contributions to the repository.

Could you briefly clarify the role of those two contributors in the project and why they are/aren't included in the authors list?

**Comment by Naeemkh** [comment]
Thank you for bringing up the discrepancies in the authorship and contributor list. We appreciate the chance to clarify the roles of both individuals.
Danielle Braun played a pivotal role during the conceptualization phase and provided key insights during meetings and discussions on how to develop the software and its underlying scientific principles. While her contributions may not be evident through direct commits or 
code contributions in the repository, her ideas, feedback, and domain expertise significantly shaped the development of the package. Given the importance of her role in the foundational stages and her sustained involvement throughout, she was deemed deserving of authorship status in the JOSS paper.
Tanujit Dey was initially scheduled to contribute through testing and other implementation-related activities. Given other commitments and opportunities he prioritized, he could not have time to complete the tasks as initially envisioned. Since his contributions were minimal and did not shape the final product, he was listed as a contributor in the DESCRIPTION file of the package but was not included as a co-author in the JOSS paper.
We hope this clarifies any concerns. We are open to any further feedback or questions you may have on this matter.

**Comment by martinmodrak** [comment]
Thanks, this clarifies everything.
