### ISSUE TITLE
Statement of Need - Compare to Existing Packages

### ISSUE THREAD

**Issue by andrewherren** [NSAPH-Software/GPCERF#79]
One of the checklist items for the JOSS review asks reviewers "Do the authors describe how this software compares to other commonly-used packages?"

The [JOSS paper draft](https://github.com/NSAPH-Software/GPCERF/blob/1e9ea19a4ba2752882a9747c84543c9bd392a346/paper/paper.md) does reference the `CausalGPS` R package (the comparison of those two methods is the subject of a separate Github issue), but mentions no other packages. A cursory search turned up the [causaldrf package](https://cran.r-project.org/web/packages/causaldrf/index.html). I am sure there are other methods implemented as R packages. It is important to convey to readers the differences between the available options and GPCERF.

**Comment by Naeemkh** [comment]
Thank you for your insightful comment. In our software paper, we discuss not only CausalGPS but also include references to **GauPro**, **mlegp**, and **GPfit** R packages. Please see the Statement of need section. Our objective is to develop a Bayesian model that inherently provides automatic uncertainty characterization and exhibits high flexibility, hence our choice of the Gaussian Process (GP) framework. Comparing this with other methodologies, like CausalDRF, which is based on a frequentist approach, falls outside the scope of our current research.

We also removed the phrase "which can be computationally demanding" from the description of the resampling approach. Additionally, the first paragraph of the statement need section has been revised to avoid making unsupported claims. While the statement about computational demand is accurate, using the CausalGPS package as an example would necessitate further elaboration, which is beyond the scope of this paper.

**Comment by andrewherren** [comment]
Thank you for the quick response! To be clear, I did notice that you had referenced `GauPro`, `mlegp`, and `GPfit` as packages for Gaussian Process estimation, what I was referring to is packages that _specifically_ do what GPCERF does: estimate the causal exposure response function.

`causaldrf` is not entirely frequentist. See section 4.5 of [this vignette](https://cran.r-project.org/web/packages/causaldrf/vignettes/Using_causaldrf.pdf), which shows how to estimate the CERF using BART (Bayesian Additive Regression Trees). Not only is BART an example of flexible Bayesian nonparametric methods which provide automatic uncertainty quantification, in fact, if you condition on the trees of BART ensemble, BART **_is_** a Gaussian process. So I do not quite understand why at least citing causaldrf is out of scope of this paper.

Furthermore, I suspect there are more than two (/ three) R packages implementing flexible Bayesian nonparametrics for exposure response functions. `causaldrf` was one that I found in a quick search. A paper introducing GPCERF would do well to present readers with all of the available options. I don't think it's necessary to do an in-depth computational comparison, but I think it's reasonable to at least _cite_ the other options.

**Comment by Naeemkh** [comment]
Thank you @andrewherren for the clarification and the insightful comment. We have added two sentences to describe `causaldrf` and its behavior. We have conducted an exhaustive search, yet we were only able to identify one more package (BCEE) that implements Bayesian nonparametric models for CERF estimation. We have included this package in our Statement of Need. Most existing packages we examined for CERF estimation are either based on frequentist approaches (e.g., [ipw](https://cran.r-project.org/web/packages/ipw/index.html), [npcausal](https://github.com/ehkennedy/npcausal), [TwangContinuous](https://cran.r-project.org/web/packages/twangContinuous/index.html) or optimization-based machine learning algorithms (e.g., [invariance causal prediction](https://cran.r-project.org/web/packages/InvariantCausalPrediction/index.html). We understand that there could be deep connections between any of these approaches to a Bayesian nonparametric model, but reviewing such connections might not be the most relevant task in this manuscript. We did find another package (`bkmr`) that utilizes kernel-based Bayesian methods to estimate effects of continuous exposure on health outcomes from observational studies. However, since it does not explicitly address the confounding effects of covariates, the estimated curves usually do not have causal interpretation. We have included this package in our manuscript as well and mentioned briefly its limitation in estimating causal ERF. We let you know when the final draft is ready for review. Thank you.

**Comment by andrewherren** [comment]
Thank you! One thing to note is that

> Due to the property of tree-based approaches, the resulting CERF is usually not smooth.

is a bit overstated in my opinion. Certainly, a single decision tree would give predictions that resemble a discontinuous step function, but the sum of 100 or 200 decision trees can often approximate a smooth function quite well (see, for example, the plot in section 4.5, page 17 of [the causaldrf vignette](https://cran.r-project.org/web/packages/causaldrf/vignettes/Using_causaldrf.pdf)).
